# A Workflow for triggering a new release.

name: Release

on: [workflow_dispatch]

permissions:
  contents: read

concurrency: "${{ github.repository }}-versioning"

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          token: ${{ secrets.TRIGGER_GITHUB_TOKEN }}
      - name: Fetch version history
        run: git fetch --tags --unshallow
      - name: Set up JDK
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
        with:
          gradle-home-cache-cleanup: true
      - name: Ensure build is green
        run: ./gradlew build
      - name: Release
        run: |
          # The following command will trigger the build.yml workflow as it pushes a release tag
          ./gradlew release
      - name: Capture version info
        run: |
          echo "Release version: $(./gradlew cV -q -Prelease.quiet)" >> $GITHUB_STEP_SUMMARY  

